// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheatreBoxOffice.DAL.Context;

#nullable disable

namespace TheatreBoxOffice.DAL.Migrations
{
    [DbContext(typeof(TheatreBoxOfficeContext))]
    partial class TheatreBoxOfficeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthorPerformance", b =>
                {
                    b.Property<long>("AuthorsId")
                        .HasColumnType("bigint");

                    b.Property<long>("PerformancesId")
                        .HasColumnType("bigint");

                    b.HasKey("AuthorsId", "PerformancesId");

                    b.HasIndex("PerformancesId");

                    b.ToTable("AuthorPerformance");
                });

            modelBuilder.Entity("GenrePerformance", b =>
                {
                    b.Property<int>("GenresId")
                        .HasColumnType("int");

                    b.Property<long>("PerformancesId")
                        .HasColumnType("bigint");

                    b.HasKey("GenresId", "PerformancesId");

                    b.HasIndex("PerformancesId");

                    b.ToTable("GenrePerformance");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TheatreBoxOffice.DAL.Entities.Author", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            FirstName = "Jerrold",
                            LastName = "Moore"
                        },
                        new
                        {
                            Id = 2L,
                            FirstName = "Rogelio",
                            LastName = "Skiles"
                        },
                        new
                        {
                            Id = 3L,
                            FirstName = "Donnell",
                            LastName = "Olson"
                        });
                });

            modelBuilder.Entity("TheatreBoxOffice.DAL.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Reggae"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Latin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rap"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Pop"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Latin"
                        });
                });

            modelBuilder.Entity("TheatreBoxOffice.DAL.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("TheatreBoxOffice.DAL.Entities.OrderTicket", b =>
                {
                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("SeatId")
                        .HasColumnType("bigint");

                    b.Property<long>("TicketPriceTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("OrderId", "SeatId", "TicketPriceTypeId");

                    b.HasIndex("SeatId");

                    b.HasIndex("TicketPriceTypeId");

                    b.ToTable("OrderTickets");
                });

            modelBuilder.Entity("TheatreBoxOffice.DAL.Entities.Performance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Performances");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Date = new DateTime(2024, 4, 8, 0, 45, 29, 452, DateTimeKind.Local).AddTicks(8602),
                            Name = "Product Usability Strategist"
                        },
                        new
                        {
                            Id = 2L,
                            Date = new DateTime(2024, 8, 18, 19, 24, 29, 295, DateTimeKind.Local).AddTicks(2167),
                            Name = "Regional Directives Consultant"
                        },
                        new
                        {
                            Id = 3L,
                            Date = new DateTime(2024, 8, 24, 2, 53, 12, 462, DateTimeKind.Local).AddTicks(9765),
                            Name = "Internal Usability Liaison"
                        },
                        new
                        {
                            Id = 4L,
                            Date = new DateTime(2024, 9, 7, 13, 24, 38, 633, DateTimeKind.Local).AddTicks(9115),
                            Name = "International Optimization Coordinator"
                        },
                        new
                        {
                            Id = 5L,
                            Date = new DateTime(2024, 7, 9, 23, 53, 33, 793, DateTimeKind.Local).AddTicks(363),
                            Name = "Corporate Creative Administrator"
                        });
                });

            modelBuilder.Entity("TheatreBoxOffice.DAL.Entities.Seat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("Row")
                        .HasColumnType("int");

                    b.Property<int>("SeatCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeatCategoryId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Number = 1,
                            Row = 1,
                            SeatCategoryId = 1
                        },
                        new
                        {
                            Id = 2L,
                            Number = 2,
                            Row = 1,
                            SeatCategoryId = 1
                        },
                        new
                        {
                            Id = 3L,
                            Number = 3,
                            Row = 1,
                            SeatCategoryId = 1
                        },
                        new
                        {
                            Id = 4L,
                            Number = 4,
                            Row = 1,
                            SeatCategoryId = 1
                        },
                        new
                        {
                            Id = 5L,
                            Number = 5,
                            Row = 1,
                            SeatCategoryId = 1
                        },
                        new
                        {
                            Id = 6L,
                            Number = 6,
                            Row = 2,
                            SeatCategoryId = 2
                        },
                        new
                        {
                            Id = 7L,
                            Number = 7,
                            Row = 2,
                            SeatCategoryId = 2
                        },
                        new
                        {
                            Id = 8L,
                            Number = 8,
                            Row = 2,
                            SeatCategoryId = 2
                        },
                        new
                        {
                            Id = 9L,
                            Number = 9,
                            Row = 2,
                            SeatCategoryId = 2
                        },
                        new
                        {
                            Id = 10L,
                            Number = 10,
                            Row = 2,
                            SeatCategoryId = 2
                        },
                        new
                        {
                            Id = 11L,
                            Number = 11,
                            Row = 3,
                            SeatCategoryId = 3
                        },
                        new
                        {
                            Id = 12L,
                            Number = 12,
                            Row = 3,
                            SeatCategoryId = 3
                        },
                        new
                        {
                            Id = 13L,
                            Number = 13,
                            Row = 3,
                            SeatCategoryId = 3
                        },
                        new
                        {
                            Id = 14L,
                            Number = 14,
                            Row = 3,
                            SeatCategoryId = 3
                        },
                        new
                        {
                            Id = 15L,
                            Number = 15,
                            Row = 3,
                            SeatCategoryId = 3
                        },
                        new
                        {
                            Id = 16L,
                            Number = 16,
                            Row = 4,
                            SeatCategoryId = 4
                        },
                        new
                        {
                            Id = 17L,
                            Number = 17,
                            Row = 4,
                            SeatCategoryId = 4
                        },
                        new
                        {
                            Id = 18L,
                            Number = 18,
                            Row = 4,
                            SeatCategoryId = 4
                        },
                        new
                        {
                            Id = 19L,
                            Number = 19,
                            Row = 4,
                            SeatCategoryId = 4
                        },
                        new
                        {
                            Id = 20L,
                            Number = 20,
                            Row = 4,
                            SeatCategoryId = 4
                        });
                });

            modelBuilder.Entity("TheatreBoxOffice.DAL.Entities.SeatCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("SeatCategory");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        },
                        new
                        {
                            Id = 3
                        },
                        new
                        {
                            Id = 4
                        });
                });

            modelBuilder.Entity("TheatreBoxOffice.DAL.Entities.TicketPriceType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("PerformanceId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("SeatCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerformanceId");

                    b.HasIndex("SeatCategoryId");

                    b.ToTable("TicketPriceType");
                });

            modelBuilder.Entity("AuthorPerformance", b =>
                {
                    b.HasOne("TheatreBoxOffice.DAL.Entities.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheatreBoxOffice.DAL.Entities.Performance", null)
                        .WithMany()
                        .HasForeignKey("PerformancesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenrePerformance", b =>
                {
                    b.HasOne("TheatreBoxOffice.DAL.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheatreBoxOffice.DAL.Entities.Performance", null)
                        .WithMany()
                        .HasForeignKey("PerformancesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheatreBoxOffice.DAL.Entities.Order", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheatreBoxOffice.DAL.Entities.OrderTicket", b =>
                {
                    b.HasOne("TheatreBoxOffice.DAL.Entities.Order", "Order")
                        .WithMany("OrderTickets")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheatreBoxOffice.DAL.Entities.Seat", "Seat")
                        .WithMany("OrderTickets")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheatreBoxOffice.DAL.Entities.TicketPriceType", "TicketPriceType")
                        .WithMany("OrderTickets")
                        .HasForeignKey("TicketPriceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Seat");

                    b.Navigation("TicketPriceType");
                });

            modelBuilder.Entity("TheatreBoxOffice.DAL.Entities.Seat", b =>
                {
                    b.HasOne("TheatreBoxOffice.DAL.Entities.SeatCategory", "SeatCategory")
                        .WithMany("Seats")
                        .HasForeignKey("SeatCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeatCategory");
                });

            modelBuilder.Entity("TheatreBoxOffice.DAL.Entities.TicketPriceType", b =>
                {
                    b.HasOne("TheatreBoxOffice.DAL.Entities.Performance", "Performance")
                        .WithMany("TicketPriceTypes")
                        .HasForeignKey("PerformanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheatreBoxOffice.DAL.Entities.SeatCategory", "SeatCategory")
                        .WithMany("TicketPriceTypes")
                        .HasForeignKey("SeatCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Performance");

                    b.Navigation("SeatCategory");
                });

            modelBuilder.Entity("TheatreBoxOffice.DAL.Entities.Order", b =>
                {
                    b.Navigation("OrderTickets");
                });

            modelBuilder.Entity("TheatreBoxOffice.DAL.Entities.Performance", b =>
                {
                    b.Navigation("TicketPriceTypes");
                });

            modelBuilder.Entity("TheatreBoxOffice.DAL.Entities.Seat", b =>
                {
                    b.Navigation("OrderTickets");
                });

            modelBuilder.Entity("TheatreBoxOffice.DAL.Entities.SeatCategory", b =>
                {
                    b.Navigation("Seats");

                    b.Navigation("TicketPriceTypes");
                });

            modelBuilder.Entity("TheatreBoxOffice.DAL.Entities.TicketPriceType", b =>
                {
                    b.Navigation("OrderTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
